[versions]
compileSdkVersion = "36"
minSdkVersion = "26"
targetSdkVersion = "35"
jvmToolchainVersion = "17"

# Plugin dependencies
android-application-plugin-version = "8.13.2"
android-library-plugin-version = "8.13.2"
kotlin-android-plugin-version = "2.2.21"
kotlin-jvm-plugin-version = "2.2.21"
kotlin-compose-plugin-version = "2.2.21"
ksp-plugin-version = "2.3.4"
hilt-plugin-version = "2.57.2"
android-navigation-safe-args-plugin-version = "2.9.7"

# Library dependencies
android-ktx-version = "1.17.0"
coroutines-android-version = "1.10.2"
android-appcompat-version = "1.7.1"
compose-bom-version = "2026.02.00"
compose-nav-version = "2.9.7"
hilt-version = "2.59.1"
room-version = "2.8.4"
material3-version = "1.5.0-alpha11"
google-font-version = "1.10.0"
mlkit-version = "19.0.1"
lifecycle-version = "2.10.0"
activity-version = "1.12.4"
hilt-navigation-version = "1.3.0"

timber-version = "5.0.1"
retrofit-version = "3.0.0"
okhttp-version = "5.3.2"
moshi-version = "1.15.2"
cropify-version = "0.5.2"
coil-version = "2.7.0"

junit-version = "4.13.2"
android-junit-version = "1.3.0"
espresso-version = "3.7.0"
turbine-version = "1.2.1"
mockk-version = "1.14.9"

[libraries]
android-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "android-ktx-version" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines-android-version" }
android-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "android-appcompat-version" }
google-fonts = { group = "androidx.compose.ui", name = "ui-text-google-fonts", version.ref = "google-font-version" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom-version" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3-version" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "compose-nav-version" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt-version" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt-version" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room-version" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room-version" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room-version" }
mlkit-text-recognition = { group = "com.google.android.gms", name = "play-services-mlkit-text-recognition", version.ref = "mlkit-version" }
lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle-version" }
lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle-version" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-version" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt-navigation-version" }

timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber-version" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit-version" }
retrofit-moshi-converter = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit-version" }
okhttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp-version" }
moshi = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshi-version" }
moshi-codegen = { group = "com.squareup.moshi", name = "moshi-kotlin-codegen", version.ref = "moshi-version" }
cropify = { group = "com.github.moyuruaizawa", name = "cropify", version.ref = "cropify-version" }
coil = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil-version" }

junit = { group = "junit", name = "junit", version.ref = "junit-version" }
android-junit = { group = "androidx.test.ext", name = "junit", version.ref = "android-junit-version" }
compose-junit = { group = "androidx.compose.ui", name = "ui-test-junit4" }
compose-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-version" }
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines-android-version" }
cashapp-turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine-version" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk-version" }

[bundles]
compose = ["compose-material3", "compose-ui-tooling-preview"]

[plugins]
android-application = { id = "com.android.application", version.ref = "android-application-plugin-version" }
android-library = { id = "com.android.library", version.ref = "android-library-plugin-version" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-android-plugin-version" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-jvm-plugin-version" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin-compose-plugin-version" }
java-library = { id = "java-library" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp-plugin-version" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt-plugin-version" }
android-navigation-safe-args = { id = "androidx.navigation.safeargs.kotlin", version.ref = "android-navigation-safe-args-plugin-version" }
